- name: check if the user is exists
  ansible.builtin.getent:
    database: passwd
    key: roboshop
  register: User_validate
  ignore_errors: true

- debug: 
    msg: "{{ User_validate}}"

- name: Add user if it doest exists
  ansible.builtin.user:
    name: roboshop
    state: present
  when: User_validate.found is not defined

- name: Check the directory exists.
  ansible.builtin.stat:
    path: /app
  register: directory

- name: create folder
  ansible.builtin.file:
    path: /app
    state: directory
  when: directory.stat.exists == False

- name: get the file from url
  ansible.builtin.get_url:
    url: curl -o /tmp/{{component}}.zip https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
    dest: /app/{{component}}

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes
  
 

